-- Sync topic_weights with all topics from ALLOWED_TOPICS
-- This ensures feedback updates will actually work

INSERT INTO topic_weights (topic) VALUES
  ('neural sde'),
  ('stochastic differential equation'),
  ('neural cde'),
  ('controlled differential equation'),
  ('rough volatility'),
  ('fractional brownian motion'),
  ('volatility surface'),
  ('implied volatility'),
  ('local volatility'),
  ('stochastic volatility'),
  ('volatility indices'),
  ('vix'),
  ('vvix'),
  ('vxn'),
  ('derivatives pricing'),
  ('options pricing'),
  ('arbitrage free modeling'),
  ('term structure modeling'),
  ('time series representation learning'),
  ('contrastive learning'),
  ('self supervised learning'),
  ('financial time series'),
  ('transformer time series'),
  ('sequence modeling'),
  ('latent variable models'),
  ('representation learning'),
  ('score based models'),
  ('diffusion models'),
  ('generative models time series'),
  ('stochastic control'),
  ('reinforcement learning trading'),
  ('optimal execution'),
  ('market microstructure'),
  ('limit order book'),
  ('statistical arbitrage'),
  ('alpha signals'),
  ('alpha generation'),
  ('regime detection'),
  ('state space models'),
  ('hidden markov models'),
  ('manifold learning'),
  ('clustering financial data'),
  ('optimal transport finance'),
  ('information geometry'),
  ('game theory finance'),
  ('quantitative finance theory')
ON CONFLICT (topic) DO NOTHING;

-- Verify the sync
SELECT COUNT(*) as total_topics FROM topic_weights;
